---
vagrantfile-local:
    vm:
        box: ubuntu-precise12042-x64-vbox43
        box_url: 'http://box.puphpet.com/ubuntu-precise12042-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.56.189
            forwarded_port:
                JgmWO6pQG9O5:
                    host: '6874'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '1024'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            1icPEyWFHZFe:
                id: vagrant-root
                source: ./
                target: /var/www
                nfs: 'true'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - multitail
        - screen
        - npm
        - vim
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: 0
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        path: /usr/local/bin
        log: /var/log/mailcatcher/mailcatcher.log
nginx:
    install: '1'
    vhosts:
        PTlhE4q4BW5W:
            server_name: jagged.dev
            server_aliases:
                - www.jagged.dev
            www_root: /var/www/jagged/public
            listen_port: '80'
            index_files:
                - index.php
                - index.html
            envvars:
                - 'APP_ENV dev'
        oXuAle6Xk8DE:
            server_name: jagged-ui.dev
            server_aliases:
                - www.jagged-ui.dev
            www_root: /var/www/jagged-ui/app
            listen_port: '80'
            index_files:
                - index.php
                - index.html
            envvars:
                - 'APP_ENV dev'
php:
    install: '1'
    version: '55'
    composer: '1'
    modules:
        php:
            - cli
            - gd
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - redis
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: America/Los_Angeles
xdebug:
    install: 0
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    install: '1'
    root_password: root
    phpmyadmin: 0
    adminer: 0
    databases:
        2LY9xVj9jXIz:
            grant:
                - ALL
            name: jagged
            host: localhost
            user: admin
            password: root
            sql_file: ''
mongodb:
    install: 0
    auth: 1
    port: '27017'
    databases: {  }
beanstalkd:
    install: '1'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: '1'
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    port: '5672'

